export const howContent = {
  es: {
    eyebrow: "CÓMO FUNCIONA / DE LA IDEA A LO HECHO",
    title: "Tú pones el objetivo.",
    accent: "Tu equipo, el trabajo.",
    intro:
      "Departify conecta el contexto de tu empresa, departamentos especializados y tus herramientas. El resultado: trabajo que puedes revisar, aprobar y seguir.",
    cta: "Explorar mi próximo equipo",
    demo: "Probar una misión",
    label: "UN PROCESO. SIEMPRE CON CONTEXTO.",
    stages: ["Entiende", "Prepara", "Te consulta", "Da seguimiento"],
    explorerEyebrow: "01 / ASÍ SE PONE EN MARCHA",
    explorerTitle: "De «necesitamos hacerlo»",
    explorerAccent: "a «listo para revisar».",
    explorerIntro:
      "Recorre el proceso: qué aportas tú, qué hace Departify y qué recibes en cada paso.",
    you: "TÚ APORTAS",
    team: "DEPARTIFY TRABAJA",
    output: "RECIBES",
    example: "EJEMPLO ILUSTRATIVO",
    next: "Siguiente paso",
    restart: "Volver al inicio",
    steps: [
      {
        title: "Comparte tu contexto",
        short: "Contexto",
        description:
          "Tu equipo empieza por entender tu empresa, cómo habla y qué quiere conseguir.",
        you: "Marca, objetivos, documentación y herramientas autorizadas.",
        team: "Organiza lo que necesita saber y conserva el contexto de tu negocio.",
        output: "Una base compartida con prioridades y reglas claras.",
        cardTitle: "Tu empresa, entendida.",
        cardRows: [
          "Marca y tono de voz",
          "Objetivos y prioridades",
          "Herramientas y permisos",
        ],
        badge: "BASE DE TRABAJO",
        note: "Solo accede a lo que tú compartes y autorizas.",
      },
      {
        title: "Define una misión",
        short: "Misión",
        description:
          "Explica el resultado que buscas. Dirección coordina las especialidades que necesites.",
        you: "Un objetivo: preparar un lanzamiento, revisar facturas o mejorar tu web.",
        team: "Divide el objetivo en tareas y prepara propuestas y entregables.",
        output: "Un plan y resultados concretos que puedes revisar.",
        cardTitle: "Preparar nuestro lanzamiento.",
        cardRows: [
          "Marketing · Propuesta de campaña",
          "SEO · Oportunidades de contenido",
          "Ventas · Borradores de seguimiento",
        ],
        badge: "DIRECCIÓN COORDINA",
        note: "Activa los departamentos que necesites; Dirección viene incluida.",
      },
      {
        title: "Aprueba lo importante",
        short: "Aprobación",
        description:
          "El trabajo llega con contexto para decidir. Las acciones sensibles siguen tus reglas.",
        you: "Tu criterio: aprobar la propuesta o pedir ajustes.",
        team: "Te presenta el resultado y espera tu permiso cuando corresponde.",
        output: "Un entregable revisado y una decisión registrada.",
        cardTitle: "Tu visto bueno cuenta.",
        cardRows: [
          "Propuesta preparada",
          "Pendiente de tu revisión",
          "Publicación sujeta a permiso",
        ],
        badge: "EL CONTROL ES TUYO",
        note: "Preparar un borrador no equivale a publicarlo.",
      },
      {
        title: "Mantén el trabajo en marcha",
        short: "Seguimiento",
        description:
          "El contexto se conserva. Puedes revisar lo hecho, las novedades y lo pendiente.",
        you: "Nuevas prioridades y decisiones cuando el equipo te las plantea.",
        team: "Da seguimiento al trabajo y señala lo que necesita tu atención.",
        output:
          "Continuidad, entregables localizables y próximos pasos claros.",
        cardTitle: "La siguiente misión parte de aquí.",
        cardRows: [
          "Entregables y decisiones",
          "Pendientes que necesitan atención",
          "Contexto para el siguiente paso",
        ],
        badge: "CONTINUIDAD",
        note: "Puedes cambiar el rumbo y los permisos cuando lo necesites.",
      },
    ],
    demoEyebrow: "02 / PRUÉBALO CON UNA MISIÓN",
    demoTitle: "Menos teoría.",
    demoAccent: "Más trabajo visible.",
    demoBody:
      "Elige una de las siete especialidades. Mira cómo una petición se transforma en tareas, un entregable y una aprobación.",
    demoNote:
      "Esta demostración es una simulación: no conecta herramientas, envía mensajes ni modifica datos.",
    guardEyebrow: "03 / LOS LÍMITES LOS MARCAS TÚ",
    guardTitle: "Delegar trabajo.",
    guardAccent: "Conservar el criterio.",
    guards: [
      [
        "Puede preparar",
        "Investigar, analizar y redactar dentro del contexto y los accesos que autorizas.",
        "Borradores, propuestas e informes.",
      ],
      [
        "Te pide aprobación",
        "Las acciones que establezcas en tus reglas, como enviar, publicar o aplicar cambios.",
        "Tú revisas antes de dar el siguiente paso.",
      ],
      [
        "No tiene acceso",
        "Herramientas, datos y espacios que no has conectado o autorizado.",
        "Los permisos delimitan su trabajo.",
      ],
    ],
    security: "Ver cómo protegemos tu empresa",
    finalEyebrow: "EMPIEZA POR LO QUE MÁS TE DESBLOQUEA.",
    finalTitle: "Una misión puede ser",
    finalAccent: "el principio de mucho.",
    finalBody:
      "Explora los siete departamentos o cuéntanos qué necesita tu empresa.",
    contact: "Hablar con el equipo",
  },
  en: {
    eyebrow: "HOW IT WORKS / FROM IDEA TO DONE",
    title: "You bring the goal.",
    accent: "Your team, the work.",
    intro:
      "Departify connects your business context, specialized departments and your tools. The result: work you can review, approve and follow.",
    cta: "Explore my next team",
    demo: "Try a mission",
    label: "ONE PROCESS. CONTEXT THROUGHOUT.",
    stages: ["Understands", "Prepares", "Checks with you", "Follows up"],
    explorerEyebrow: "01 / GETTING STARTED",
    explorerTitle: "From “we need this”",
    explorerAccent: "to “ready to review”.",
    explorerIntro:
      "Explore the process: what you contribute, what Departify does and what you receive at every step.",
    you: "YOU CONTRIBUTE",
    team: "DEPARTIFY WORKS",
    output: "YOU RECEIVE",
    example: "ILLUSTRATIVE EXAMPLE",
    next: "Next step",
    restart: "Back to the start",
    steps: [
      {
        title: "Share your context",
        short: "Context",
        description:
          "Your team starts by understanding your business, its voice and its goals.",
        you: "Brand, goals, documentation and authorized tools.",
        team: "Organizes what it needs to know and retains your business context.",
        output: "A shared foundation with clear priorities and rules.",
        cardTitle: "Your business, understood.",
        cardRows: [
          "Brand and tone of voice",
          "Goals and priorities",
          "Tools and permissions",
        ],
        badge: "SHARED FOUNDATION",
        note: "It only accesses what you share and authorize.",
      },
      {
        title: "Define a mission",
        short: "Mission",
        description:
          "Explain the result you want. Direction coordinates the specialties you need.",
        you: "A goal: prepare a launch, review invoices or improve your website.",
        team: "Breaks the goal into tasks and prepares proposals and deliverables.",
        output: "A plan and tangible results for you to review.",
        cardTitle: "Prepare our launch.",
        cardRows: [
          "Marketing · Campaign proposal",
          "SEO · Content opportunities",
          "Sales · Follow-up drafts",
        ],
        badge: "DIRECTION COORDINATES",
        note: "Activate the departments you need. Direction is included.",
      },
      {
        title: "Approve what matters",
        short: "Approval",
        description:
          "Work comes with context so you can decide. Sensitive actions follow your rules.",
        you: "Your judgment: approve the proposal or request changes.",
        team: "Presents the result and waits for permission when required.",
        output: "A reviewed deliverable and a recorded decision.",
        cardTitle: "Your approval matters.",
        cardRows: [
          "Proposal prepared",
          "Awaiting your review",
          "Publishing requires permission",
        ],
        badge: "YOU ARE IN CONTROL",
        note: "Preparing a draft does not mean publishing it.",
      },
      {
        title: "Keep work moving",
        short: "Follow-up",
        description:
          "Context carries forward. Review completed work, updates and outstanding items.",
        you: "New priorities and decisions when the team brings them to you.",
        team: "Follows up on work and flags what needs your attention.",
        output: "Continuity, accessible deliverables and clear next steps.",
        cardTitle: "The next mission starts here.",
        cardRows: [
          "Deliverables and decisions",
          "Items needing attention",
          "Context for the next step",
        ],
        badge: "CONTINUITY",
        note: "You can adjust direction and permissions whenever needed.",
      },
    ],
    demoEyebrow: "02 / TRY A MISSION",
    demoTitle: "Less theory.",
    demoAccent: "More visible work.",
    demoBody:
      "Choose one of seven specialties. See a request become tasks, a deliverable and an approval.",
    demoNote:
      "This demo is a simulation. It does not connect tools, send messages or change data.",
    guardEyebrow: "03 / YOU SET THE LIMITS",
    guardTitle: "Delegate work.",
    guardAccent: "Keep your judgment.",
    guards: [
      [
        "Can prepare",
        "Research, analyze and draft within the context and access you authorize.",
        "Drafts, proposals and reports.",
      ],
      [
        "Asks for approval",
        "Actions covered by your rules, such as sending, publishing or applying changes.",
        "You review before the next step.",
      ],
      [
        "Has no access",
        "Tools, data and spaces you have not connected or authorized.",
        "Permissions define the boundaries.",
      ],
    ],
    security: "See how we protect your business",
    finalEyebrow: "START WHERE IT MAKES THE BIGGEST DIFFERENCE.",
    finalTitle: "One mission can be",
    finalAccent: "the start of much more.",
    finalBody:
      "Explore the seven departments or tell us what your business needs.",
    contact: "Talk to our team",
  },
};
